#!/usr/bin/env python3
"""
slop_scan.py — static scanner for code-noise patterns in JS/TS source files.

Usage:
  slop_scan.py [FILE ...]           # scan specific files, print report
  slop_scan.py --diff               # scan files changed in git diff
  slop_scan.py FILE --apply         # apply cleanup, print result to stdout
  slop_scan.py [FILE ...] --json    # machine-readable output

Exit codes: 0 = clean, 1 = findings detected, 2 = error.
"""

import re
import sys
import json
import subprocess
from pathlib import Path
from typing import NamedTuple


# ── Pattern libraries ──────────────────────────────────────────────────────────

# Category A: verbs whose presence in a comment suggests it mirrors the next line.
MIRROR_VERBS = frozenset({
    'return', 'increment', 'decrement', 'call', 'fetch', 'get', 'set',
    'update', 'create', 'delete', 'remove', 'add', 'push', 'pop',
    'import', 'export', 'define', 'declare', 'initialize', 'check',
    'validate', 'parse', 'format', 'convert', 'log', 'print', 'throw',
    'catch', 'handle', 'map', 'filter', 'reduce', 'sort', 'find',
    'render', 'dispatch', 'emit', 'send', 'receive', 'open', 'close',
    'read', 'write', 'load', 'save', 'reset', 'clear', 'show', 'hide',
    'append', 'prepend', 'insert', 'assign', 'store', 'retrieve',
})

STOP_WORDS = frozenset({
    'the', 'a', 'an', 'is', 'to', 'of', 'and', 'or', 'in', 'for',
    'on', 'by', 'with', 'it', 'its', 'this', 'that', 'we', 'our',
    'from', 'into', 'as', 'at', 'if', 'be', 'new', 'value', 'data',
})

# Category B: template/boilerplate phrases.
TEMPLATE_RES = [
    re.compile(r'this (function|method|class|component) is responsible for', re.I),
    re.compile(r'in this code we will', re.I),
    re.compile(r'the following (function|method|class)', re.I),
    re.compile(r'the purpose of this (function|method|class) is', re.I),
    re.compile(r'this component renders', re.I),
    re.compile(r'helper function that', re.I),
    re.compile(r'this (function|method|class) (takes|accepts|receives)', re.I),
    re.compile(r'used (throughout|across) the (application|app|codebase)', re.I),
    re.compile(r'this is a (helper|utility|wrapper) (function|method)', re.I),
]

# Category C: AI meta-phrases.
AI_META_RES = [
    re.compile(r'as an ai( language model)?[,\s]', re.I),
    re.compile(r'(note|warning):\s*this was generated by (ai|claude|chatgpt|copilot)', re.I),
    re.compile(r'\bai[- ]generated\b', re.I),
    re.compile(r'generated by (claude|chatgpt|copilot|gpt[-\s]?\d)', re.I),
    re.compile(r'generated with the help of (claude|chatgpt|copilot|gpt|ai)', re.I),
    re.compile(r'note: i cannot\b', re.I),
    re.compile(r"i (don'?t|do not) have access to\b", re.I),
    re.compile(r'note: please (review|verify|check) (this|the)', re.I),
]

# Category D: debug-labeled comments (exact match after stripping comment syntax).
DEBUG_EXACT = frozenset({
    'debug', 'temp', 'temporary', 'temporary test', 'just for testing',
    'remove before commit', 'todo remove', 'test debug',
})

# Tool directives — ALWAYS preserved (partial match is enough).
TOOL_DIRECTIVES = (
    'eslint-disable', 'eslint-enable', '@ts-ignore', '@ts-expect-error',
    '@ts-nocheck', 'prettier-ignore', 'biome-ignore', 'stylelint-disable',
    'c8 ignore', 'istanbul ignore', 'noinspection', 'vitest-ignore',
    '@jest-environment',
)

# Maintenance markers — ALWAYS preserved.
MAINTENANCE_PREFIXES = (
    'TODO:', 'FIXME:', 'HACK:', 'NOTE:', 'XXX:', 'BUG:', 'WORKAROUND:',
)

EMOJI_RE = re.compile(
    '[\U0001F300-\U0001FFFF'
    '\U00002600-\U000027BF'
    '\U00002700-\U000027BF'
    '\U0001F100-\U0001F1FF'
    '️'    # variation selector-16 (emoji presentation)
    '‍'    # zero-width joiner (used in multi-part emoji sequences)
    '\U0001F3FB-\U0001F3FF'  # skin tone modifiers
    ']'
)

CONSOLE_RE = re.compile(r'\bconsole\.(log|warn|error|info|debug)\s*\(')

SUPPORTED_EXTENSIONS = frozenset({'.js', '.ts', '.jsx', '.tsx', '.mjs', '.cjs'})

GENERATED_MARKERS = ('@generated', 'code generated', 'do not edit', 'auto-generated')


# ── Data types ─────────────────────────────────────────────────────────────────

class Finding(NamedTuple):
    line_no: int
    category: str
    text: str
    description: str


# ── Preservation checks ────────────────────────────────────────────────────────

def is_preserved(line: str) -> bool:
    """Return True if this line must never be touched regardless of content."""
    text = line.strip()
    lower = text.lower()

    for directive in TOOL_DIRECTIVES:
        if directive in lower:
            return True

    body = re.sub(r'^(/{1,3}|\*+|#+)\s*', '', text).strip()
    for marker in MAINTENANCE_PREFIXES:
        if body.upper().startswith(marker):
            return True

    if re.search(r'\b(copyright|license|mit\b|apache\b|gnu\b|mozilla\b)', lower):
        return True

    return False


def is_comment_start(line: str) -> bool:
    s = line.strip()
    return s.startswith('//') or s.startswith('/*') or s.startswith('*')


def extract_comment_body(line: str) -> str:
    """Strip comment syntax characters and return bare text."""
    s = line.strip()
    body = re.sub(r'^(/{1,3}|\*+|#+)\s*', '', s)
    return body.strip()


# ── Category helpers ───────────────────────────────────────────────────────────

def next_nonempty_code_line(lines: list[str], after_idx: int) -> str:
    """First non-blank, non-comment line after after_idx (0-based)."""
    for line in lines[after_idx + 1:]:
        s = line.strip()
        if s and not is_comment_start(line):
            return s
    return ''


def is_mirror(comment_body: str, code_line: str) -> bool:
    """
    True if comment_body essentially restates what code_line does.
    Heuristic: comment contains a mirror verb AND shares at least one
    non-trivial token with the code line.
    """
    if not comment_body or not code_line:
        return False
    c_words = set(re.findall(r'[a-zA-Z]+', comment_body.lower()))
    k_words = set(re.findall(r'[a-zA-Z]+', code_line.lower()))
    if not (c_words & MIRROR_VERBS):
        return False
    shared = (c_words & k_words) - STOP_WORDS - MIRROR_VERBS
    return len(shared) >= 1


def check_a(line: str, lines: list[str], idx: int) -> bool:
    """Category A: comment mirrors the immediately following code line."""
    s = line.strip()
    if not (s.startswith('//') or s.startswith('#')):
        return False
    body = extract_comment_body(line)
    if not body:
        return False
    next_code = next_nonempty_code_line(lines, idx)
    return is_mirror(body, next_code)


def check_b(line: str) -> bool:
    """Category B: template/boilerplate phrase."""
    body = extract_comment_body(line)
    return any(p.search(body) for p in TEMPLATE_RES)


def check_c(line: str) -> bool:
    """Category C: AI meta-phrase."""
    body = extract_comment_body(line)
    return any(p.search(body) for p in AI_META_RES)


def check_d(line: str) -> bool:
    """Category D: debug-labeled comment (exact match only)."""
    body = extract_comment_body(line).lower().strip()
    return body in DEBUG_EXACT


def check_e(line: str) -> bool:
    """Category E: emoji in a non-UI context (comment or console.* call)."""
    if not EMOJI_RE.search(line):
        return False
    s = line.strip()
    if is_comment_start(line):
        return True
    if CONSOLE_RE.search(s):
        # Only if the emoji is inside the string argument, not in JSX
        return '<' not in s
    return False


def strip_emojis(line: str) -> str:
    """Remove emojis and clean up whitespace left behind."""
    cleaned = EMOJI_RE.sub('', line)
    # Collapse double spaces to single
    cleaned = re.sub(r'  +', ' ', cleaned)
    # Remove trailing space before a closing string quote followed by , ) ; or end
    cleaned = re.sub(r" ([\"'])(?=\s*[,);])", r'\1', cleaned)
    # Remove trailing space before end-of-line (inside or outside strings)
    cleaned = re.sub(r' $', '', cleaned, flags=re.MULTILINE)
    if line.endswith('\n') and not cleaned.endswith('\n'):
        cleaned += '\n'
    return cleaned


# ── File scanner ───────────────────────────────────────────────────────────────

def is_generated(lines: list[str]) -> bool:
    """Return True if the file appears to be auto-generated (skip it)."""
    header = '\n'.join(l.lower() for l in lines[:5])
    return any(m in header for m in GENERATED_MARKERS)


def scan_file(filepath: Path) -> tuple[list[Finding], list[str]]:
    """
    Scan filepath for noise patterns A–E.
    Returns (findings, original_lines).
    """
    try:
        content = filepath.read_text(encoding='utf-8')
    except (OSError, UnicodeDecodeError) as exc:
        print(f'ERROR: cannot read {filepath}: {exc}', file=sys.stderr)
        return [], []

    lines = content.splitlines(keepends=True)

    if is_generated(lines):
        return [], lines

    findings: list[Finding] = []

    for idx, line in enumerate(lines):
        line_no = idx + 1
        if not line.strip():
            continue
        if is_preserved(line):
            continue

        if is_comment_start(line):
            if check_a(line, lines, idx):
                findings.append(Finding(line_no, 'A', line.rstrip(), 'mirrors next code line'))
            elif check_b(line):
                findings.append(Finding(line_no, 'B', line.rstrip(), 'template/boilerplate phrase'))
            elif check_c(line):
                findings.append(Finding(line_no, 'C', line.rstrip(), 'AI meta-phrase'))
            elif check_d(line):
                findings.append(Finding(line_no, 'D', line.rstrip(), 'debug-labeled comment'))
            elif check_e(line):
                findings.append(Finding(line_no, 'E', line.rstrip(), 'emoji in comment'))
        else:
            if check_e(line):
                findings.append(Finding(line_no, 'E', line.rstrip(), 'emoji in non-UI string'))

    return findings, lines


# ── Cleanup application ────────────────────────────────────────────────────────

def apply_cleanup(lines: list[str], findings: list[Finding]) -> str:
    """
    Remove lines flagged A–D; strip emojis from lines flagged E.
    Collapses any resulting consecutive blank lines to at most one.
    """
    remove_set = {f.line_no for f in findings if f.category != 'E'}
    emoji_set = {f.line_no for f in findings if f.category == 'E'}

    stage: list[str] = []
    for idx, line in enumerate(lines):
        line_no = idx + 1
        if line_no in remove_set:
            continue
        if line_no in emoji_set:
            cleaned = strip_emojis(line)
            body = cleaned.strip()
            # Drop the line if cleaning left only comment punctuation
            if body in ('//', '#', '/**', '*/', '/*'):
                continue
            stage.append(cleaned)
        else:
            stage.append(line)

    # Collapse consecutive blank lines
    result: list[str] = []
    prev_blank = False
    for line in stage:
        blank = not line.strip()
        if blank and prev_blank:
            continue
        result.append(line)
        prev_blank = blank

    return ''.join(result)


# ── Reporting ──────────────────────────────────────────────────────────────────

CATEGORY_LABELS = {
    'A': 'Redundant comment (mirrors next line)',
    'B': 'Template/boilerplate phrase',
    'C': 'AI meta-phrase',
    'D': 'Debug-labeled comment',
    'E': 'Emoji in non-UI context',
}


def print_report(all_findings: dict[str, list[Finding]]) -> None:
    total = sum(len(v) for v in all_findings.values())
    if total == 0:
        print('No code-noise patterns detected.')
        return

    counts: dict[str, int] = {}
    for filepath, findings in all_findings.items():
        if not findings:
            continue
        bar = '─' * max(0, 50 - len(filepath))
        print(f'\n── {filepath} {bar}')
        for f in findings:
            print(f'  [{f.category}] line {f.line_no:>4}  {f.text[:80]}')
        for f in findings:
            counts[f.category] = counts.get(f.category, 0) + 1

    print(f'\nSUMMARY')
    print(f'  Files with findings: {sum(1 for v in all_findings.values() if v)}')
    print(f'  Total findings:      {total}')
    for cat in sorted(counts):
        print(f'    [{cat}] {CATEGORY_LABELS[cat]}: {counts[cat]}')
    print()
    print('Run with --apply on a single file to output the cleaned version.')
    print('Use /ai-clean-diff in Claude Code to apply changes interactively.')


def print_json(all_findings: dict[str, list[Finding]]) -> None:
    out = {
        fp: [
            {'line': f.line_no, 'category': f.category,
             'description': f.description, 'text': f.text}
            for f in findings
        ]
        for fp, findings in all_findings.items()
    }
    print(json.dumps(out, indent=2))


# ── Git helpers ────────────────────────────────────────────────────────────────

def get_diff_files() -> list[Path]:
    """Return JS/TS files changed in the current git diff."""
    for cmd in (
        ['git', 'diff', '--name-only', 'HEAD'],
        ['git', 'diff', 'origin/main...HEAD', '--name-only'],
        ['git', 'diff', 'origin/master...HEAD', '--name-only'],
    ):
        try:
            out = subprocess.check_output(cmd, stderr=subprocess.DEVNULL, text=True)
            files = [Path(p) for p in out.splitlines() if p]
            if files:
                return [f for f in files if f.suffix in SUPPORTED_EXTENSIONS and f.exists()]
        except subprocess.CalledProcessError:
            continue
    return []


# ── Entry point ────────────────────────────────────────────────────────────────

def main(argv: list[str]) -> int:
    use_diff = '--diff' in argv
    apply_mode = '--apply' in argv
    json_mode = '--json' in argv
    file_args = [a for a in argv if not a.startswith('--')]

    if apply_mode and len(file_args) != 1:
        print('ERROR: --apply requires exactly one file argument.', file=sys.stderr)
        return 2

    if use_diff:
        paths = get_diff_files()
        if not paths:
            print('No changed JS/TS files found in git diff.')
            return 0
    elif file_args:
        paths = [Path(f) for f in file_args]
    else:
        print(__doc__)
        return 2

    # Filter to supported extensions only
    paths = [p for p in paths if p.suffix in SUPPORTED_EXTENSIONS]

    if apply_mode:
        path = paths[0]
        findings, lines = scan_file(path)
        print(apply_cleanup(lines, findings), end='')
        return 0

    all_findings: dict[str, list[Finding]] = {}
    for path in paths:
        findings, _ = scan_file(path)
        all_findings[str(path)] = findings

    if json_mode:
        print_json(all_findings)
    else:
        print_report(all_findings)

    has_findings = any(all_findings.values())
    return 1 if has_findings else 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
