#!/usr/bin/env python3
"""Lightweight AI slop pattern scanner for CI/CD pipelines.
Scans JS/TS files for the same categories defined in skills/ai-slop-scan/SKILL.md"""

import re
import sys
import os

REDUNDANT_COMMENT_PATTERNS = [
    r'^//\s*(return|increment|decrement|set|call|get|add|remove|update|delete|create|check|handle|fetch|send|load|save|log|print|render|init|setup|cleanup)\s+\w',
]

TEMPLATE_PHRASES = [
    r'this function is responsible for',
    r'this method is responsible for',
    r'in this code we will',
    r'the following function',
    r'the purpose of this function is',
    r'this component renders',
    r'helper function that',
]

AI_META_PHRASES = [
    r'as an ai',
    r'as an ai language model',
    r'generated by (claude|chatgpt|copilot|openai)',
    r'ai-generated',
    r'note: i cannot',
    r"i don't have access to",
]

DEBUG_LABELS = [
    r'^//\s*(debug|temp|temporary|remove before commit|just for testing)\s*$',
    r'^//\s*todo remove\s*$',
]

EMOJI_PATTERN = re.compile(
    r'[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF'
    r'\U0001F1E0-\U0001F1FF\U00002700-\U000027BF\U0000FE00-\U0000FE0F'
    r'\U0001F900-\U0001F9FF\U00002600-\U000026FF]+'
)

PRESERVED_PATTERNS = [
    r'^//\s*(TODO|FIXME|HACK|NOTE):',
    r'eslint-disable',
    r'@ts-ignore',
    r'prettier-ignore',
    r'@generated',
    r'copyright',
]

findings = []

def is_preserved(line):
    l = line.strip().lower()
    for p in PRESERVED_PATTERNS:
        if re.search(p, line, re.IGNORECASE):
            return True
    return False

def scan_file(filepath):
    file_findings = []
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            lines = f.readlines()
    except FileNotFoundError:
        return []

    for i, line in enumerate(lines, 1):
        stripped = line.strip()
        if is_preserved(stripped):
            continue
        # Category B: template phrases
        for p in TEMPLATE_PHRASES:
            if re.search(p, stripped, re.IGNORECASE) and stripped.startswith('//'):
                file_findings.append((i, 'B', stripped))
                break
        # Category C: AI meta phrases
        for p in AI_META_PHRASES:
            if re.search(p, stripped, re.IGNORECASE) and stripped.startswith('//'):
                file_findings.append((i, 'C', stripped))
                break
        # Category D: debug labels
        for p in DEBUG_LABELS:
            if re.match(p, stripped, re.IGNORECASE):
                file_findings.append((i, 'D', stripped))
                break
        # Category E: emojis in non-UI context
        if EMOJI_PATTERN.search(stripped):
            if 'console.' in stripped or (stripped.startswith('//') and not '<' in stripped):
                file_findings.append((i, 'E', stripped))

    return file_findings

def main():
    files = [f for f in sys.argv[1:] if os.path.isfile(f)]
    if not files:
        print('No files to scan.')
        sys.exit(0)

    total = 0
    report_lines = []
    for filepath in files:
        result = scan_file(filepath)
        if result:
            report_lines.append(f'\n── {filepath} ──')
            for lineno, cat, text in result:
                report_lines.append(f'  [{cat}] line {lineno:>4}  {text[:80]}')
                total += 1

    summary = f'\nSUMMARY: {len(files)} files scanned, {total} findings.'
    report_lines.append(summary)
    report = '\n'.join(report_lines)

    print(report)
    with open('/tmp/slop-report.txt', 'w') as f:
        f.write(report)

    if total > 0:
        print('\nRun /ai-clean-diff to fix flagged patterns.')
        sys.exit(1)

main()
